# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Generate App Store screenshots with matching artwork for iPhone and iPad"
  lane :screenshots do
    sh("python3", File.expand_path("../scripts/app-store-screenshots.py", __dir__))
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "bowtie2.xcodeproj")
    build_app(scheme: "bowtie2")
    upload_to_testflight
  end

  desc "Upload symbols to sentry"
  lane :upload_symbols do
    download_dsyms
    sentry_debug_files_upload(
      org_slug: "jake-org",
      project_slug: "bowtie",
      path: lane_context[SharedValues::DSYM_PATHS],
    )
  end
end
